version: '3.8'

services:
  clipboard-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shared-clipboard-server
    ports:
      - "8080:8080"
    environment:
      - RUST_LOG=info
      - RUST_BACKTRACE=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/api/clipboard || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # Логирование
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    # Ограничения ресурсов
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: '0.5'
        reservations:
          memory: 64M
          cpus: '0.1'
